included:
    - Sources
    - Development
excluded:
    - Tests

function_body_length:
    warning: 75
    error: 100

large_tuple:
    warning: 4

line_length:
    warning: 150
    error: 200
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true

nesting:
    type_level:
        warning: 2

disabled_rules:
    - unused_optional_binding
    - trailing_whitespace
    - function_parameter_count
opt_in_rules:
    - sorted_imports
